// Generated by `cabal run pcbgen -- sketcher`; do not edit.
// The numbers come from toolkit/src/Sketch/Catalogue.hs.
(function (root) {
  var data = {
  "format": "module-sketch",
  "version": 2,
  "kinds": [
    {
      "id": "knob",
      "label": "Knob"
    },
    {
      "id": "jack",
      "label": "Jack"
    },
    {
      "id": "switch",
      "label": "Switch"
    },
    {
      "id": "led",
      "label": "LED"
    }
  ],
  "maxColumns": 6,
  "maxRows": 6,
  "widthForColumns": [
    {
      "columns": 1,
      "hp": 4
    },
    {
      "columns": 2,
      "hp": 8
    },
    {
      "columns": 3,
      "hp": 10
    },
    {
      "columns": 4,
      "hp": 14
    },
    {
      "columns": 5,
      "hp": 16
    },
    {
      "columns": 6,
      "hp": 20
    }
  ],
  "why": "At 15 mm spacing a 100 mm board leaves 80.61 mm of travel for control centres, so 6 rows fit; 7 would space them 13.44 mm apart and two 3.5 mm jacks need 13.6 mm. Columns stop at 6 because that already needs the widest panel the module policy allows."
};
  if (typeof module !== 'undefined' && module.exports) { module.exports = data; }
  root.SKETCH_CATALOGUE = data;
})(typeof globalThis !== 'undefined' ? globalThis : this);
