// Generated by `cabal run pcbgen -- sketcher`; do not edit. The numbers
// come from toolkit/src/Sketch/*.hs and Block/Eurorack.hs.
(function (root) {
  var data = {
  "format": "pcbgen-sketch",
  "version": 1,
  "hardware": [
    {
      "id": "jack-ts",
      "name": "3.5 mm TS jack, switched (Thonkiconn, QingPu WQP-WQP518MA)",
      "role": "jack",
      "hole": 6.4,
      "frontBody": {
        "shape": "circle",
        "d": 8
      },
      "frontAccess": {
        "shape": "circle",
        "d": 10
      },
      "courtyard": {
        "x1": -5,
        "y1": -1.42,
        "x2": 5,
        "y2": 12.98
      },
      "footprint": "Connector_Audio:Jack_3.5mm_QingPu_WQP-PJ398SM_Vertical_CircularHoles",
      "anchor": {
        "x": 0,
        "y": 0
      },
      "rotations": [
        0,
        90,
        180,
        270
      ],
      "reservesCell": true,
      "defaultRotation": 0,
      "height": 9,
      "status": "in-use",
      "frontEvidence": "unverified",
      "source": "KiCad 10 Connector_Audio footprint (courtyard, anchor); docs/MECHANICAL.md hardware standard (hole, height)",
      "notes": "Front envelopes are estimates: an M6 knurled nut of about 8 mm and a plug barrel of about 10 mm. Nuts and washers are ordered separately."
    },
    {
      "id": "jack-trs",
      "name": "3.5 mm TRS jack, unswitched (Stereo Thonkiconn, QingPu WQP-WQP419GR)",
      "role": "jack",
      "hole": 6.4,
      "frontBody": {
        "shape": "circle",
        "d": 8
      },
      "frontAccess": {
        "shape": "circle",
        "d": 10
      },
      "courtyard": {
        "x1": -5.5,
        "y1": -1.42,
        "x2": 5.5,
        "y2": 12.98
      },
      "footprint": null,
      "anchor": {
        "x": 0,
        "y": 0
      },
      "rotations": [
        0,
        90,
        180,
        270
      ],
      "reservesCell": true,
      "defaultRotation": 0,
      "height": 10,
      "status": "proposed",
      "frontEvidence": "unverified",
      "source": "docs/MECHANICAL.md hardware standard; kicad-footprints PR 823 (never merged) for the 0.5 mm wider courtyard",
      "notes": "No switch contact. Body height 9 to 10 mm is unverified; at 10 mm it touches the panel. Footprint still to be added to lib/footprints/pcbgen.pretty."
    },
    {
      "id": "pot-9mm",
      "name": "9 mm pot, Alpha RD901F-40 with a Davies 1900h-class knob",
      "role": "pot",
      "hole": 7.2,
      "frontBody": {
        "shape": "circle",
        "d": 12
      },
      "frontAccess": {
        "shape": "circle",
        "d": 18
      },
      "courtyard": {
        "x1": -8.65,
        "y1": -6.41,
        "x2": 5.1,
        "y2": 6.41
      },
      "footprint": "Potentiometer_THT:Potentiometer_Alpha_RD901F-40-00D_Single_Vertical",
      "anchor": {
        "x": 7.5,
        "y": 2.5
      },
      "rotations": [
        0,
        90,
        180,
        270
      ],
      "reservesCell": true,
      "defaultRotation": 90,
      "height": 10,
      "status": "in-use",
      "frontEvidence": "unverified",
      "source": "KiCad 10 Potentiometer_THT footprint (courtyard, anchor); docs/MECHANICAL.md (hole, stack); Thonk knob page (12 mm base)",
      "notes": "The 18 mm access circle is a finger estimate for the ergonomic mockup, not a measurement. The pot sets the panel height."
    },
    {
      "id": "toggle-spdt",
      "name": "Sub-mini toggle SPDT on-off-on (Dailywell 2MS3T1B1M2QES)",
      "role": "switch",
      "hole": 5,
      "frontBody": {
        "shape": "circle",
        "d": 8
      },
      "frontAccess": {
        "shape": "rect",
        "w": 10,
        "h": 20
      },
      "courtyard": {
        "x1": -4.315,
        "y1": -4.57,
        "x2": 4.315,
        "y2": 4.57
      },
      "footprint": null,
      "anchor": {
        "x": 0,
        "y": 0
      },
      "rotations": [
        0,
        90,
        180,
        270
      ],
      "reservesCell": true,
      "defaultRotation": 0,
      "height": 9.84,
      "status": "proposed",
      "frontEvidence": "unverified",
      "source": "docs/MECHANICAL.md hardware standard (Dailywell 2M datasheet callouts)",
      "notes": "Throw is along y at rotation 0. The access rectangle allows for the 9.4 mm bat swinging plus a fingertip. Footprint still to be drawn."
    },
    {
      "id": "toggle-dpdt",
      "name": "Sub-mini toggle DPDT on-off-on (Dailywell 2MD3T1B1M2QES)",
      "role": "switch",
      "hole": 5,
      "frontBody": {
        "shape": "circle",
        "d": 8
      },
      "frontAccess": {
        "shape": "rect",
        "w": 10,
        "h": 20
      },
      "courtyard": {
        "x1": -4.82,
        "y1": -4.57,
        "x2": 4.82,
        "y2": 4.57
      },
      "footprint": null,
      "anchor": {
        "x": 0,
        "y": 0
      },
      "rotations": [
        0,
        90,
        180,
        270
      ],
      "reservesCell": true,
      "defaultRotation": 0,
      "height": 9.84,
      "status": "proposed",
      "frontEvidence": "unverified",
      "source": "docs/MECHANICAL.md hardware standard (9.14 mm body for two poles)",
      "notes": "The 4.06 mm row spacing of the two pole rows must be checked on the drawing before the footprint is drawn."
    },
    {
      "id": "led-3mm",
      "name": "3 mm indicator LED, bare in the panel hole",
      "role": "led",
      "hole": 3.2,
      "frontBody": {
        "shape": "circle",
        "d": 3.2
      },
      "frontAccess": null,
      "courtyard": {
        "x1": -2.42,
        "y1": -2.21,
        "x2": 2.42,
        "y2": 2.21
      },
      "footprint": "LED_THT:LED_D3.0mm",
      "anchor": {
        "x": 1.27,
        "y": 0
      },
      "rotations": [
        0,
        90,
        180,
        270
      ],
      "reservesCell": false,
      "defaultRotation": 0,
      "height": 8,
      "status": "proposed",
      "frontEvidence": "proposed",
      "source": "KiCad 10 LED_THT footprint (courtyard, anchor); docs/MECHANICAL.md (leads hold the body 7 to 9 mm off the board)",
      "notes": "Meant to sit diagonally off the jack it reports, inside that jack's cell; the offset is what the sketcher's checks decide. A bipolar red/green part has the same geometry."
    }
  ],
  "profiles": [
    {
      "id": "candidate-15",
      "pitch": {
        "x": 15,
        "y": 15
      },
      "firstRow": 20,
      "status": "candidate",
      "note": "15 mm knob spacing proposed in docs/MECHANICAL.md; needs the ergonomic mockup with cables installed."
    },
    {
      "id": "candidate-15.24",
      "pitch": {
        "x": 15.24,
        "y": 15.24
      },
      "firstRow": 20,
      "status": "candidate",
      "note": "Three nominal HP; the panel width table and fixed rail holes still apply, so columns do not continue across modules."
    },
    {
      "id": "thonkiconn-13.7",
      "pitch": {
        "x": 13.7,
        "y": 13.7
      },
      "firstRow": 20,
      "status": "candidate",
      "note": "The minimum Thonkiconn column pitch from the official footprint pads; dense, and not shown to give comfortable access."
    }
  ],
  "form": {
    "panelHeight": 128.5,
    "pcbHeight": 100,
    "pcbTop": 14.25,
    "railHoleDiameter": 3.2,
    "railKeepoutRadius": 3.5,
    "minCentreEdgeDistance": 6,
    "policyHP": {
      "min": 4,
      "max": 20
    },
    "doepferTable": [
      1,
      2,
      4,
      6,
      8,
      10,
      12,
      14,
      16,
      18,
      20,
      22,
      28,
      42
    ]
  },
  "skeletons": [
    {
      "hp": 1,
      "panelWidth": 5,
      "boardWidth": 3,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 2,
      "panelWidth": 9.8,
      "boardWidth": 7.800000000000001,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 3,
      "panelWidth": 14.94,
      "boardWidth": 12.94,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 4,
      "panelWidth": 20,
      "boardWidth": 18,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 5,
      "panelWidth": 25.099999999999998,
      "boardWidth": 23.099999999999998,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        17.66
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 6,
      "panelWidth": 30,
      "boardWidth": 28,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        22.740000000000002
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 7,
      "panelWidth": 35.260000000000005,
      "boardWidth": 33.260000000000005,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        27.82
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 8,
      "panelWidth": 40.3,
      "boardWidth": 38.3,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        32.9
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 9,
      "panelWidth": 45.42,
      "boardWidth": 43.42,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        37.980000000000004
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 10,
      "panelWidth": 50.5,
      "boardWidth": 48.5,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        43.06
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 11,
      "panelWidth": 55.580000000000005,
      "boardWidth": 53.580000000000005,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        48.14
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 12,
      "panelWidth": 60.6,
      "boardWidth": 58.6,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        53.22
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 13,
      "panelWidth": 65.74000000000001,
      "boardWidth": 63.74000000000001,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        58.3
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 14,
      "panelWidth": 70.8,
      "boardWidth": 68.8,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        63.38
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 15,
      "panelWidth": 75.9,
      "boardWidth": 73.9,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        68.46000000000001
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 16,
      "panelWidth": 80.9,
      "boardWidth": 78.9,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        73.54
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 17,
      "panelWidth": 86.06,
      "boardWidth": 84.06,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        78.62
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 18,
      "panelWidth": 91.3,
      "boardWidth": 89.3,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        83.7
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 19,
      "panelWidth": 96.22,
      "boardWidth": 94.22,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        88.78
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 20,
      "panelWidth": 101.3,
      "boardWidth": 99.3,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        93.86
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 21,
      "panelWidth": 106.38000000000001,
      "boardWidth": 104.38000000000001,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        98.94
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 22,
      "panelWidth": 111.4,
      "boardWidth": 109.4,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        104.02
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 23,
      "panelWidth": 116.54,
      "boardWidth": 114.54,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        109.1
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 24,
      "panelWidth": 121.62,
      "boardWidth": 119.62,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        114.18
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 25,
      "panelWidth": 126.7,
      "boardWidth": 124.7,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        119.26
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 26,
      "panelWidth": 131.78,
      "boardWidth": 129.78,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        124.34
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 27,
      "panelWidth": 136.85999999999999,
      "boardWidth": 134.85999999999999,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        129.42000000000002
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 28,
      "panelWidth": 141.9,
      "boardWidth": 139.9,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        134.5
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 29,
      "panelWidth": 147.01999999999998,
      "boardWidth": 145.01999999999998,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        139.58
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 30,
      "panelWidth": 152.1,
      "boardWidth": 150.1,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        144.66
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 31,
      "panelWidth": 157.17999999999998,
      "boardWidth": 155.17999999999998,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        149.74
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 32,
      "panelWidth": 162.26,
      "boardWidth": 160.26,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        154.82
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 33,
      "panelWidth": 167.34,
      "boardWidth": 165.34,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        159.9
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 34,
      "panelWidth": 172.42,
      "boardWidth": 170.42,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        164.98
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 35,
      "panelWidth": 177.5,
      "boardWidth": 175.5,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        170.06
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 36,
      "panelWidth": 182.57999999999998,
      "boardWidth": 180.57999999999998,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        175.14000000000001
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 37,
      "panelWidth": 187.66,
      "boardWidth": 185.66,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        180.22
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 38,
      "panelWidth": 192.73999999999998,
      "boardWidth": 190.73999999999998,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        185.3
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 39,
      "panelWidth": 197.82,
      "boardWidth": 195.82,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        190.38
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 40,
      "panelWidth": 202.89999999999998,
      "boardWidth": 200.89999999999998,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        195.46
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 41,
      "panelWidth": 207.98,
      "boardWidth": 205.98,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        200.54
      ],
      "railHolesY": [
        3,
        125.5
      ]
    },
    {
      "hp": 42,
      "panelWidth": 213,
      "boardWidth": 211,
      "boardHeight": 100,
      "boardOrigin": {
        "x": 1,
        "y": 14.25
      },
      "railHolesX": [
        7.5,
        205.62
      ],
      "railHolesY": [
        3,
        125.5
      ]
    }
  ],
  "skeletonRule": "panelWidth from Doepfer's table or HP x 5.08 - 0.3; board 1 mm inside each side, 100 mm tall, centred; rail holes at x 7.5 and 7.5 + (HP - 3) x 5.08 (only when HP > 4), y 3 and 125.5"
};
  if (typeof module !== 'undefined' && module.exports) { module.exports = data; }
  root.PCBGEN_CATALOGUE = data;
})(typeof globalThis !== 'undefined' ? globalThis : this);
