// Generated by `cabal run pcbgen -- sketcher`; do not edit. The numbers
// come from toolkit/src/Sketch/*.hs and Block/Eurorack.hs.
(function (root) {
  var data = {
  "valid": [
    {
      "name": "sparse-mixed",
      "sketch": {
        "format": "pcbgen-sketch",
        "version": 1,
        "name": "Sparse mixed fixture",
        "status": "provisional",
        "hp": 8,
        "grid": {
          "origin": {
            "x": 12.65,
            "y": 20
          },
          "pitch": {
            "x": 15,
            "y": 15
          },
          "profile": "candidate-15"
        },
        "controls": [
          {
            "id": "level",
            "hardware": "pot-9mm",
            "cell": {
              "col": 0,
              "row": 0
            },
            "rotation": 90,
            "label": "LEVEL",
            "group": "ch1"
          },
          {
            "id": "in",
            "hardware": "jack-ts",
            "cell": {
              "col": 0,
              "row": 1
            },
            "label": "IN",
            "group": "ch1"
          },
          {
            "id": "out",
            "hardware": "jack-ts",
            "cell": {
              "col": 1,
              "row": 1
            },
            "label": "OUT",
            "group": "ch1"
          },
          {
            "id": "out-led",
            "hardware": "led-3mm",
            "cell": {
              "col": 1,
              "row": 1
            },
            "offset": {
              "x": 6,
              "y": -6
            },
            "group": "ch1"
          },
          {
            "id": "cycle",
            "hardware": "toggle-spdt",
            "cell": {
              "col": 1,
              "row": 3
            },
            "label": "CYCLE"
          },
          {
            "id": "freq",
            "hardware": "pot-9mm",
            "cell": {
              "col": 0,
              "row": 5
            },
            "span": {
              "cols": 2,
              "rows": 1
            },
            "label": "FREQ"
          }
        ],
        "groups": [
          {
            "id": "ch1",
            "label": "Channel 1"
          }
        ],
        "notes": [
          "Fixture for the S1 gate: sparse placement, a multi-cell control and an indicator inside a jack's cell."
        ]
      },
      "text": "{\n  \"format\": \"pcbgen-sketch\",\n  \"version\": 1,\n  \"name\": \"Sparse mixed fixture\",\n  \"status\": \"provisional\",\n  \"hp\": 8,\n  \"grid\": {\n    \"origin\": {\n      \"x\": 12.65,\n      \"y\": 20\n    },\n    \"pitch\": {\n      \"x\": 15,\n      \"y\": 15\n    },\n    \"profile\": \"candidate-15\"\n  },\n  \"controls\": [\n    {\n      \"id\": \"level\",\n      \"hardware\": \"pot-9mm\",\n      \"cell\": {\n        \"col\": 0,\n        \"row\": 0\n      },\n      \"rotation\": 90,\n      \"label\": \"LEVEL\",\n      \"group\": \"ch1\"\n    },\n    {\n      \"id\": \"in\",\n      \"hardware\": \"jack-ts\",\n      \"cell\": {\n        \"col\": 0,\n        \"row\": 1\n      },\n      \"label\": \"IN\",\n      \"group\": \"ch1\"\n    },\n    {\n      \"id\": \"out\",\n      \"hardware\": \"jack-ts\",\n      \"cell\": {\n        \"col\": 1,\n        \"row\": 1\n      },\n      \"label\": \"OUT\",\n      \"group\": \"ch1\"\n    },\n    {\n      \"id\": \"out-led\",\n      \"hardware\": \"led-3mm\",\n      \"cell\": {\n        \"col\": 1,\n        \"row\": 1\n      },\n      \"offset\": {\n        \"x\": 6,\n        \"y\": -6\n      },\n      \"group\": \"ch1\"\n    },\n    {\n      \"id\": \"cycle\",\n      \"hardware\": \"toggle-spdt\",\n      \"cell\": {\n        \"col\": 1,\n        \"row\": 3\n      },\n      \"label\": \"CYCLE\"\n    },\n    {\n      \"id\": \"freq\",\n      \"hardware\": \"pot-9mm\",\n      \"cell\": {\n        \"col\": 0,\n        \"row\": 5\n      },\n      \"span\": {\n        \"cols\": 2,\n        \"rows\": 1\n      },\n      \"label\": \"FREQ\"\n    }\n  ],\n  \"groups\": [\n    {\n      \"id\": \"ch1\",\n      \"label\": \"Channel 1\"\n    }\n  ],\n  \"notes\": [\n    \"Fixture for the S1 gate: sparse placement, a multi-cell control and an indicator inside a jack's cell.\"\n  ]\n}\n",
      "expected": {
        "panelWidth": 40.3,
        "boardOrigin": {
          "x": 1,
          "y": 14.25
        },
        "railHoles": [
          {
            "x": 7.5,
            "y": 3
          },
          {
            "x": 7.5,
            "y": 125.5
          },
          {
            "x": 32.9,
            "y": 3
          },
          {
            "x": 32.9,
            "y": 125.5
          }
        ],
        "controls": [
          {
            "id": "level",
            "centre": {
              "x": 12.65,
              "y": 20
            },
            "board": {
              "x": 11.65,
              "y": 5.75
            },
            "footprintOrigin": {
              "x": 9.15,
              "y": 13.25
            },
            "rotation": 90,
            "courtyard": {
              "x1": 6.24,
              "y1": 14.9,
              "x2": 19.060000000000002,
              "y2": 28.65
            },
            "frontBody": {
              "shape": "circle",
              "d": 12
            },
            "frontAccess": {
              "shape": "circle",
              "d": 18
            }
          },
          {
            "id": "in",
            "centre": {
              "x": 12.65,
              "y": 35
            },
            "board": {
              "x": 11.65,
              "y": 20.75
            },
            "footprintOrigin": {
              "x": 11.65,
              "y": 20.75
            },
            "rotation": 0,
            "courtyard": {
              "x1": 7.65,
              "y1": 33.58,
              "x2": 17.65,
              "y2": 47.980000000000004
            },
            "frontBody": {
              "shape": "circle",
              "d": 8
            },
            "frontAccess": {
              "shape": "circle",
              "d": 10
            }
          },
          {
            "id": "out",
            "centre": {
              "x": 27.65,
              "y": 35
            },
            "board": {
              "x": 26.65,
              "y": 20.75
            },
            "footprintOrigin": {
              "x": 26.65,
              "y": 20.75
            },
            "rotation": 0,
            "courtyard": {
              "x1": 22.65,
              "y1": 33.58,
              "x2": 32.65,
              "y2": 47.980000000000004
            },
            "frontBody": {
              "shape": "circle",
              "d": 8
            },
            "frontAccess": {
              "shape": "circle",
              "d": 10
            }
          },
          {
            "id": "out-led",
            "centre": {
              "x": 33.65,
              "y": 29
            },
            "board": {
              "x": 32.65,
              "y": 14.75
            },
            "footprintOrigin": {
              "x": 31.38,
              "y": 14.75
            },
            "rotation": 0,
            "courtyard": {
              "x1": 31.229999999999997,
              "y1": 26.79,
              "x2": 36.07,
              "y2": 31.21
            },
            "frontBody": {
              "shape": "circle",
              "d": 3.2
            },
            "frontAccess": null
          },
          {
            "id": "cycle",
            "centre": {
              "x": 27.65,
              "y": 65
            },
            "board": {
              "x": 26.65,
              "y": 50.75
            },
            "footprintOrigin": {
              "x": 26.65,
              "y": 50.75
            },
            "rotation": 0,
            "courtyard": {
              "x1": 23.334999999999997,
              "y1": 60.43,
              "x2": 31.965,
              "y2": 69.57
            },
            "frontBody": {
              "shape": "circle",
              "d": 8
            },
            "frontAccess": {
              "shape": "rect",
              "w": 10,
              "h": 20
            }
          },
          {
            "id": "freq",
            "centre": {
              "x": 20.15,
              "y": 95
            },
            "board": {
              "x": 19.15,
              "y": 80.75
            },
            "footprintOrigin": {
              "x": 11.649999999999999,
              "y": 78.25
            },
            "rotation": 0,
            "courtyard": {
              "x1": 11.499999999999998,
              "y1": 88.59,
              "x2": 25.25,
              "y2": 101.41
            },
            "frontBody": {
              "shape": "circle",
              "d": 12
            },
            "frontAccess": {
              "shape": "circle",
              "d": 18
            }
          }
        ],
        "findings": [
          {
            "kind": "provisional-grid",
            "severity": "note",
            "controls": [],
            "message": "grid profile \"candidate-15\" is a candidate pitch, not an approved one; this sketch is provisional"
          },
          {
            "kind": "unverified-front",
            "severity": "note",
            "controls": [
              "in",
              "out"
            ],
            "message": "jack-ts: nut, knob or cable envelope is an estimate awaiting the mockup (2 controls)"
          },
          {
            "kind": "unverified-front",
            "severity": "note",
            "controls": [
              "level",
              "freq"
            ],
            "message": "pot-9mm: nut, knob or cable envelope is an estimate awaiting the mockup (2 controls)"
          },
          {
            "kind": "unverified-front",
            "severity": "note",
            "controls": [
              "cycle"
            ],
            "message": "toggle-spdt: nut, knob or cable envelope is an estimate awaiting the mockup (1 control)"
          },
          {
            "kind": "no-footprint",
            "severity": "note",
            "controls": [
              "cycle"
            ],
            "message": "toggle-spdt: no footprint exists yet, so a design cannot place it until lib/footprints gains one"
          },
          {
            "kind": "proposed-hardware",
            "severity": "note",
            "controls": [
              "cycle"
            ],
            "message": "toggle-spdt: proposed in the hardware standard, not yet designed in or measured"
          },
          {
            "kind": "proposed-hardware",
            "severity": "note",
            "controls": [
              "out-led"
            ],
            "message": "led-3mm: proposed in the hardware standard, not yet designed in or measured"
          }
        ]
      }
    },
    {
      "name": "conflicts",
      "sketch": {
        "format": "pcbgen-sketch",
        "version": 1,
        "name": "Conflicts fixture",
        "status": "provisional",
        "hp": 6,
        "grid": {
          "origin": {
            "x": 7.5,
            "y": 20
          },
          "pitch": {
            "x": 15,
            "y": 15
          },
          "profile": "candidate-15"
        },
        "controls": [
          {
            "id": "a",
            "hardware": "jack-ts",
            "cell": {
              "col": 0,
              "row": 0
            }
          },
          {
            "id": "b",
            "hardware": "jack-ts",
            "cell": {
              "col": 0,
              "row": 0
            }
          },
          {
            "id": "low",
            "hardware": "jack-ts",
            "cell": {
              "col": 0,
              "row": 6
            }
          },
          {
            "id": "far",
            "hardware": "pot-9mm",
            "cell": {
              "col": 2,
              "row": 1
            }
          },
          {
            "id": "shift",
            "hardware": "led-3mm",
            "cell": {
              "col": 1,
              "row": 1
            },
            "offset": {
              "x": 0,
              "y": 8
            }
          },
          {
            "id": "p1",
            "hardware": "pot-9mm",
            "cell": {
              "col": 0,
              "row": 3
            },
            "rotation": 90
          },
          {
            "id": "p2",
            "hardware": "pot-9mm",
            "cell": {
              "col": 1,
              "row": 3
            },
            "rotation": 90
          },
          {
            "id": "top",
            "hardware": "toggle-spdt",
            "cell": {
              "col": 0,
              "row": -1
            }
          }
        ],
        "notes": [
          "Fixture: every conflict kind at least once. Nothing here is a design."
        ]
      },
      "text": "{\n  \"format\": \"pcbgen-sketch\",\n  \"version\": 1,\n  \"name\": \"Conflicts fixture\",\n  \"status\": \"provisional\",\n  \"hp\": 6,\n  \"grid\": {\n    \"origin\": {\n      \"x\": 7.5,\n      \"y\": 20\n    },\n    \"pitch\": {\n      \"x\": 15,\n      \"y\": 15\n    },\n    \"profile\": \"candidate-15\"\n  },\n  \"controls\": [\n    {\n      \"id\": \"a\",\n      \"hardware\": \"jack-ts\",\n      \"cell\": {\n        \"col\": 0,\n        \"row\": 0\n      }\n    },\n    {\n      \"id\": \"b\",\n      \"hardware\": \"jack-ts\",\n      \"cell\": {\n        \"col\": 0,\n        \"row\": 0\n      }\n    },\n    {\n      \"id\": \"low\",\n      \"hardware\": \"jack-ts\",\n      \"cell\": {\n        \"col\": 0,\n        \"row\": 6\n      }\n    },\n    {\n      \"id\": \"far\",\n      \"hardware\": \"pot-9mm\",\n      \"cell\": {\n        \"col\": 2,\n        \"row\": 1\n      }\n    },\n    {\n      \"id\": \"shift\",\n      \"hardware\": \"led-3mm\",\n      \"cell\": {\n        \"col\": 1,\n        \"row\": 1\n      },\n      \"offset\": {\n        \"x\": 0,\n        \"y\": 8\n      }\n    },\n    {\n      \"id\": \"p1\",\n      \"hardware\": \"pot-9mm\",\n      \"cell\": {\n        \"col\": 0,\n        \"row\": 3\n      },\n      \"rotation\": 90\n    },\n    {\n      \"id\": \"p2\",\n      \"hardware\": \"pot-9mm\",\n      \"cell\": {\n        \"col\": 1,\n        \"row\": 3\n      },\n      \"rotation\": 90\n    },\n    {\n      \"id\": \"top\",\n      \"hardware\": \"toggle-spdt\",\n      \"cell\": {\n        \"col\": 0,\n        \"row\": -1\n      }\n    }\n  ],\n  \"notes\": [\n    \"Fixture: every conflict kind at least once. Nothing here is a design.\"\n  ]\n}\n",
      "expected": {
        "panelWidth": 30,
        "boardOrigin": {
          "x": 1,
          "y": 14.25
        },
        "railHoles": [
          {
            "x": 7.5,
            "y": 3
          },
          {
            "x": 7.5,
            "y": 125.5
          },
          {
            "x": 22.740000000000002,
            "y": 3
          },
          {
            "x": 22.740000000000002,
            "y": 125.5
          }
        ],
        "controls": [
          {
            "id": "a",
            "centre": {
              "x": 7.5,
              "y": 20
            },
            "board": {
              "x": 6.5,
              "y": 5.75
            },
            "footprintOrigin": {
              "x": 6.5,
              "y": 5.75
            },
            "rotation": 0,
            "courtyard": {
              "x1": 2.5,
              "y1": 18.58,
              "x2": 12.5,
              "y2": 32.980000000000004
            },
            "frontBody": {
              "shape": "circle",
              "d": 8
            },
            "frontAccess": {
              "shape": "circle",
              "d": 10
            }
          },
          {
            "id": "b",
            "centre": {
              "x": 7.5,
              "y": 20
            },
            "board": {
              "x": 6.5,
              "y": 5.75
            },
            "footprintOrigin": {
              "x": 6.5,
              "y": 5.75
            },
            "rotation": 0,
            "courtyard": {
              "x1": 2.5,
              "y1": 18.58,
              "x2": 12.5,
              "y2": 32.980000000000004
            },
            "frontBody": {
              "shape": "circle",
              "d": 8
            },
            "frontAccess": {
              "shape": "circle",
              "d": 10
            }
          },
          {
            "id": "low",
            "centre": {
              "x": 7.5,
              "y": 110
            },
            "board": {
              "x": 6.5,
              "y": 95.75
            },
            "footprintOrigin": {
              "x": 6.5,
              "y": 95.75
            },
            "rotation": 0,
            "courtyard": {
              "x1": 2.5,
              "y1": 108.58,
              "x2": 12.5,
              "y2": 122.98
            },
            "frontBody": {
              "shape": "circle",
              "d": 8
            },
            "frontAccess": {
              "shape": "circle",
              "d": 10
            }
          },
          {
            "id": "far",
            "centre": {
              "x": 37.5,
              "y": 35
            },
            "board": {
              "x": 36.5,
              "y": 20.75
            },
            "footprintOrigin": {
              "x": 29,
              "y": 18.25
            },
            "rotation": 0,
            "courtyard": {
              "x1": 28.85,
              "y1": 28.59,
              "x2": 42.6,
              "y2": 41.41
            },
            "frontBody": {
              "shape": "circle",
              "d": 12
            },
            "frontAccess": {
              "shape": "circle",
              "d": 18
            }
          },
          {
            "id": "shift",
            "centre": {
              "x": 22.5,
              "y": 43
            },
            "board": {
              "x": 21.5,
              "y": 28.75
            },
            "footprintOrigin": {
              "x": 20.23,
              "y": 28.75
            },
            "rotation": 0,
            "courtyard": {
              "x1": 20.08,
              "y1": 40.79,
              "x2": 24.92,
              "y2": 45.21
            },
            "frontBody": {
              "shape": "circle",
              "d": 3.2
            },
            "frontAccess": null
          },
          {
            "id": "p1",
            "centre": {
              "x": 7.5,
              "y": 65
            },
            "board": {
              "x": 6.5,
              "y": 50.75
            },
            "footprintOrigin": {
              "x": 3.9999999999999996,
              "y": 58.25
            },
            "rotation": 90,
            "courtyard": {
              "x1": 1.0899999999999999,
              "y1": 59.9,
              "x2": 13.91,
              "y2": 73.65
            },
            "frontBody": {
              "shape": "circle",
              "d": 12
            },
            "frontAccess": {
              "shape": "circle",
              "d": 18
            }
          },
          {
            "id": "p2",
            "centre": {
              "x": 22.5,
              "y": 65
            },
            "board": {
              "x": 21.5,
              "y": 50.75
            },
            "footprintOrigin": {
              "x": 19,
              "y": 58.25
            },
            "rotation": 90,
            "courtyard": {
              "x1": 16.09,
              "y1": 59.9,
              "x2": 28.91,
              "y2": 73.65
            },
            "frontBody": {
              "shape": "circle",
              "d": 12
            },
            "frontAccess": {
              "shape": "circle",
              "d": 18
            }
          },
          {
            "id": "top",
            "centre": {
              "x": 7.5,
              "y": 5
            },
            "board": {
              "x": 6.5,
              "y": -9.25
            },
            "footprintOrigin": {
              "x": 6.5,
              "y": -9.25
            },
            "rotation": 0,
            "courtyard": {
              "x1": 3.1849999999999996,
              "y1": 0.4299999999999997,
              "x2": 11.815000000000001,
              "y2": 9.57
            },
            "frontBody": {
              "shape": "circle",
              "d": 8
            },
            "frontAccess": {
              "shape": "rect",
              "w": 10,
              "h": 20
            }
          }
        ],
        "findings": [
          {
            "kind": "outside-board-zone",
            "severity": "conflict",
            "controls": [
              "low"
            ],
            "message": "low: its body behind the panel leaves the PCB zone (panel x 1 mm to 29 mm, y 14.25 mm to 114.25 mm)"
          },
          {
            "kind": "outside-panel",
            "severity": "conflict",
            "controls": [
              "far"
            ],
            "message": "far: its 7.2 mm hole leaves the 30 mm x 128.5 mm panel"
          },
          {
            "kind": "outside-board-zone",
            "severity": "conflict",
            "controls": [
              "far"
            ],
            "message": "far: its body behind the panel leaves the PCB zone (panel x 1 mm to 29 mm, y 14.25 mm to 114.25 mm)"
          },
          {
            "kind": "offset-too-large",
            "severity": "conflict",
            "controls": [
              "shift"
            ],
            "message": "shift: offset (0 mm, 8 mm) leaves its cell; keep it within half a pitch"
          },
          {
            "kind": "outside-board-zone",
            "severity": "conflict",
            "controls": [
              "top"
            ],
            "message": "top: its body behind the panel leaves the PCB zone (panel x 1 mm to 29 mm, y 14.25 mm to 114.25 mm)"
          },
          {
            "kind": "rail-keepout",
            "severity": "conflict",
            "controls": [
              "top"
            ],
            "message": "top: stands within 3.5 mm of the rail screw at (7.5 mm, 3 mm)"
          },
          {
            "kind": "cell-overlap",
            "severity": "conflict",
            "controls": [
              "a",
              "b"
            ],
            "message": "a and b reserve the same cell (0, 0)"
          },
          {
            "kind": "front-overlap",
            "severity": "conflict",
            "controls": [
              "a",
              "b"
            ],
            "message": "a and b collide in front of the panel (nut, knob or bushing)"
          },
          {
            "kind": "back-overlap",
            "severity": "conflict",
            "controls": [
              "a",
              "b"
            ],
            "message": "a and b have overlapping footprint courtyards behind the panel"
          },
          {
            "kind": "access-overlap",
            "severity": "warning",
            "controls": [
              "p1",
              "p2"
            ],
            "message": "p1 and p2: finger, cable or bat room overlaps; check on the mockup"
          },
          {
            "kind": "provisional-grid",
            "severity": "note",
            "controls": [],
            "message": "grid profile \"candidate-15\" is a candidate pitch, not an approved one; this sketch is provisional"
          },
          {
            "kind": "unverified-front",
            "severity": "note",
            "controls": [
              "a",
              "b",
              "low"
            ],
            "message": "jack-ts: nut, knob or cable envelope is an estimate awaiting the mockup (3 controls)"
          },
          {
            "kind": "unverified-front",
            "severity": "note",
            "controls": [
              "far",
              "p1",
              "p2"
            ],
            "message": "pot-9mm: nut, knob or cable envelope is an estimate awaiting the mockup (3 controls)"
          },
          {
            "kind": "unverified-front",
            "severity": "note",
            "controls": [
              "top"
            ],
            "message": "toggle-spdt: nut, knob or cable envelope is an estimate awaiting the mockup (1 control)"
          },
          {
            "kind": "no-footprint",
            "severity": "note",
            "controls": [
              "top"
            ],
            "message": "toggle-spdt: no footprint exists yet, so a design cannot place it until lib/footprints gains one"
          },
          {
            "kind": "proposed-hardware",
            "severity": "note",
            "controls": [
              "top"
            ],
            "message": "toggle-spdt: proposed in the hardware standard, not yet designed in or measured"
          },
          {
            "kind": "proposed-hardware",
            "severity": "note",
            "controls": [
              "shift"
            ],
            "message": "led-3mm: proposed in the hardware standard, not yet designed in or measured"
          }
        ]
      }
    },
    {
      "name": "empty-4hp",
      "sketch": {
        "format": "pcbgen-sketch",
        "version": 1,
        "name": "Empty 4HP",
        "status": "provisional",
        "hp": 4,
        "grid": {
          "origin": {
            "x": 10,
            "y": 20
          },
          "pitch": {
            "x": 15,
            "y": 15
          },
          "profile": "candidate-15"
        },
        "controls": []
      },
      "text": "{\n  \"format\": \"pcbgen-sketch\",\n  \"version\": 1,\n  \"name\": \"Empty 4HP\",\n  \"status\": \"provisional\",\n  \"hp\": 4,\n  \"grid\": {\n    \"origin\": {\n      \"x\": 10,\n      \"y\": 20\n    },\n    \"pitch\": {\n      \"x\": 15,\n      \"y\": 15\n    },\n    \"profile\": \"candidate-15\"\n  },\n  \"controls\": []\n}\n",
      "expected": {
        "panelWidth": 20,
        "boardOrigin": {
          "x": 1,
          "y": 14.25
        },
        "railHoles": [
          {
            "x": 7.5,
            "y": 3
          },
          {
            "x": 7.5,
            "y": 125.5
          }
        ],
        "controls": [],
        "findings": [
          {
            "kind": "provisional-grid",
            "severity": "note",
            "controls": [],
            "message": "grid profile \"candidate-15\" is a candidate pitch, not an approved one; this sketch is provisional"
          }
        ]
      }
    }
  ],
  "invalid": [
    {
      "name": "wrong version",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 2, \"hp\": 6, \"grid\": }{\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"controls\": []"
    },
    {
      "name": "wrong format",
      "text": "{\"format\": \"kicad\", \"version\": 1, \"hp\": 6, \"grid\": }{\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"controls\": []"
    },
    {
      "name": "missing hp",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": }{\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"controls\": []"
    },
    {
      "name": "hp not a panel width",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 0, \"controls\": []}"
    },
    {
      "name": "duplicate control id",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"controls\": [{\"id\": \"in\", \"hardware\": \"jack-ts\", \"cell\": {\"col\": 0, \"row\": 0}}, {\"id\": \"in\", \"hardware\": \"jack-ts\", \"cell\": {\"col\": 1, \"row\": 0}}]}"
    },
    {
      "name": "id with a space",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"controls\": [{\"id\": \"in put\", \"hardware\": \"jack-ts\", \"cell\": {\"col\": 0, \"row\": 0}}]}"
    },
    {
      "name": "unknown hardware",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"controls\": [{\"id\": \"x\", \"hardware\": \"banana\", \"cell\": {\"col\": 0, \"row\": 0}}]}"
    },
    {
      "name": "non-finite coordinate",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"hp\": 6, \"grid\": {\"origin\": {\"x\": 1e999, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"controls\": []}"
    },
    {
      "name": "NaN literal",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"hp\": 6, \"grid\": {\"origin\": {\"x\": NaN, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"controls\": []}"
    },
    {
      "name": "zero pitch",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"hp\": 6, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 0, \"y\": 15}}, \"controls\": []}"
    },
    {
      "name": "negative pitch",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"hp\": 6, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": -15}}, \"controls\": []}"
    },
    {
      "name": "zero span",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"controls\": [{\"id\": \"x\", \"hardware\": \"pot-9mm\", \"cell\": {\"col\": 0, \"row\": 0}, \"span\": {\"cols\": 0, \"rows\": 1}}]}"
    },
    {
      "name": "fractional cell",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"controls\": [{\"id\": \"x\", \"hardware\": \"pot-9mm\", \"cell\": {\"col\": 0.5, \"row\": 0}}]}"
    },
    {
      "name": "rotation not allowed",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"controls\": [{\"id\": \"x\", \"hardware\": \"pot-9mm\", \"cell\": {\"col\": 0, \"row\": 0}, \"rotation\": 45}]}"
    },
    {
      "name": "unknown top-level field",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"controls\": [], \"netlist\": []}"
    },
    {
      "name": "unknown control field",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"controls\": [{\"id\": \"x\", \"hardware\": \"pot-9mm\", \"cell\": {\"col\": 0, \"row\": 0}, \"lcsc\": \"C1\"}]}"
    },
    {
      "name": "offset with an extra axis",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"controls\": [{\"id\": \"x\", \"hardware\": \"pot-9mm\", \"cell\": {\"col\": 0, \"row\": 0}, \"offset\": {\"x\": 0, \"y\": 0, \"z\": 1}}]}"
    },
    {
      "name": "group not declared",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"controls\": [{\"id\": \"x\", \"hardware\": \"pot-9mm\", \"cell\": {\"col\": 0, \"row\": 0}, \"group\": \"ch9\"}]}"
    },
    {
      "name": "status invented",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"status\": \"manufacturing-ready\", \"controls\": []}"
    },
    {
      "name": "not an object",
      "text": "[]"
    },
    {
      "name": "truncated text",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"hp\": 6"
    },
    {
      "name": "trailing comma",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"controls\": [],}"
    },
    {
      "name": "duplicate key",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 1, \"grid\": {\"origin\": {\"x\": 7.5, \"y\": 20}, \"pitch\": {\"x\": 15, \"y\": 15}}, \"hp\": 6, \"hp\": 8, \"controls\": []}"
    },
    {
      "name": "empty text",
      "text": ""
    }
  ],
  "gridDefaults": [
    {
      "hp": 1,
      "profile": "candidate-15",
      "origin": {
        "x": 2.5,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 1,
      "profile": "candidate-15.24",
      "origin": {
        "x": 2.5,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 1,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 2.5,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 2,
      "profile": "candidate-15",
      "origin": {
        "x": 4.9,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 2,
      "profile": "candidate-15.24",
      "origin": {
        "x": 4.9,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 2,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 4.9,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 3,
      "profile": "candidate-15",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 3,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 3,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 4,
      "profile": "candidate-15",
      "origin": {
        "x": 10,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 4,
      "profile": "candidate-15.24",
      "origin": {
        "x": 10,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 4,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 10,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 5,
      "profile": "candidate-15",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 5,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 5,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 1,
      "rows": 6
    },
    {
      "hp": 6,
      "profile": "candidate-15",
      "origin": {
        "x": 7.5,
        "y": 20
      },
      "columns": 2,
      "rows": 6
    },
    {
      "hp": 6,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.38,
        "y": 20
      },
      "columns": 2,
      "rows": 6
    },
    {
      "hp": 6,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 8.15,
        "y": 20
      },
      "columns": 2,
      "rows": 6
    },
    {
      "hp": 7,
      "profile": "candidate-15",
      "origin": {
        "x": 10.13,
        "y": 20
      },
      "columns": 2,
      "rows": 6
    },
    {
      "hp": 7,
      "profile": "candidate-15.24",
      "origin": {
        "x": 10.01,
        "y": 20
      },
      "columns": 2,
      "rows": 6
    },
    {
      "hp": 7,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 10.78,
        "y": 20
      },
      "columns": 2,
      "rows": 6
    },
    {
      "hp": 8,
      "profile": "candidate-15",
      "origin": {
        "x": 12.65,
        "y": 20
      },
      "columns": 2,
      "rows": 6
    },
    {
      "hp": 8,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.53,
        "y": 20
      },
      "columns": 2,
      "rows": 6
    },
    {
      "hp": 8,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 6.45,
        "y": 20
      },
      "columns": 3,
      "rows": 6
    },
    {
      "hp": 9,
      "profile": "candidate-15",
      "origin": {
        "x": 7.71,
        "y": 20
      },
      "columns": 3,
      "rows": 6
    },
    {
      "hp": 9,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 3,
      "rows": 6
    },
    {
      "hp": 9,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 9.01,
        "y": 20
      },
      "columns": 3,
      "rows": 6
    },
    {
      "hp": 10,
      "profile": "candidate-15",
      "origin": {
        "x": 10.25,
        "y": 20
      },
      "columns": 3,
      "rows": 6
    },
    {
      "hp": 10,
      "profile": "candidate-15.24",
      "origin": {
        "x": 10.01,
        "y": 20
      },
      "columns": 3,
      "rows": 6
    },
    {
      "hp": 10,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 11.55,
        "y": 20
      },
      "columns": 3,
      "rows": 6
    },
    {
      "hp": 11,
      "profile": "candidate-15",
      "origin": {
        "x": 12.79,
        "y": 20
      },
      "columns": 3,
      "rows": 6
    },
    {
      "hp": 11,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 3,
      "rows": 6
    },
    {
      "hp": 11,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 7.24,
        "y": 20
      },
      "columns": 4,
      "rows": 6
    },
    {
      "hp": 12,
      "profile": "candidate-15",
      "origin": {
        "x": 7.8,
        "y": 20
      },
      "columns": 4,
      "rows": 6
    },
    {
      "hp": 12,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.44,
        "y": 20
      },
      "columns": 4,
      "rows": 6
    },
    {
      "hp": 12,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 9.75,
        "y": 20
      },
      "columns": 4,
      "rows": 6
    },
    {
      "hp": 13,
      "profile": "candidate-15",
      "origin": {
        "x": 10.37,
        "y": 20
      },
      "columns": 4,
      "rows": 6
    },
    {
      "hp": 13,
      "profile": "candidate-15.24",
      "origin": {
        "x": 10.01,
        "y": 20
      },
      "columns": 4,
      "rows": 6
    },
    {
      "hp": 13,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 12.32,
        "y": 20
      },
      "columns": 4,
      "rows": 6
    },
    {
      "hp": 14,
      "profile": "candidate-15",
      "origin": {
        "x": 12.9,
        "y": 20
      },
      "columns": 4,
      "rows": 6
    },
    {
      "hp": 14,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.54,
        "y": 20
      },
      "columns": 4,
      "rows": 6
    },
    {
      "hp": 14,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 8,
        "y": 20
      },
      "columns": 5,
      "rows": 6
    },
    {
      "hp": 15,
      "profile": "candidate-15",
      "origin": {
        "x": 7.95,
        "y": 20
      },
      "columns": 5,
      "rows": 6
    },
    {
      "hp": 15,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 5,
      "rows": 6
    },
    {
      "hp": 15,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 10.55,
        "y": 20
      },
      "columns": 5,
      "rows": 6
    },
    {
      "hp": 16,
      "profile": "candidate-15",
      "origin": {
        "x": 10.45,
        "y": 20
      },
      "columns": 5,
      "rows": 6
    },
    {
      "hp": 16,
      "profile": "candidate-15.24",
      "origin": {
        "x": 9.97,
        "y": 20
      },
      "columns": 5,
      "rows": 6
    },
    {
      "hp": 16,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 6.2,
        "y": 20
      },
      "columns": 6,
      "rows": 6
    },
    {
      "hp": 17,
      "profile": "candidate-15",
      "origin": {
        "x": 13.03,
        "y": 20
      },
      "columns": 5,
      "rows": 6
    },
    {
      "hp": 17,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 5,
      "rows": 6
    },
    {
      "hp": 17,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 8.78,
        "y": 20
      },
      "columns": 6,
      "rows": 6
    },
    {
      "hp": 18,
      "profile": "candidate-15",
      "origin": {
        "x": 8.15,
        "y": 20
      },
      "columns": 6,
      "rows": 6
    },
    {
      "hp": 18,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.55,
        "y": 20
      },
      "columns": 6,
      "rows": 6
    },
    {
      "hp": 18,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 11.4,
        "y": 20
      },
      "columns": 6,
      "rows": 6
    },
    {
      "hp": 19,
      "profile": "candidate-15",
      "origin": {
        "x": 10.61,
        "y": 20
      },
      "columns": 6,
      "rows": 6
    },
    {
      "hp": 19,
      "profile": "candidate-15.24",
      "origin": {
        "x": 10.01,
        "y": 20
      },
      "columns": 6,
      "rows": 6
    },
    {
      "hp": 19,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 7.01,
        "y": 20
      },
      "columns": 7,
      "rows": 6
    },
    {
      "hp": 20,
      "profile": "candidate-15",
      "origin": {
        "x": 13.15,
        "y": 20
      },
      "columns": 6,
      "rows": 6
    },
    {
      "hp": 20,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 6,
      "rows": 6
    },
    {
      "hp": 20,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 9.55,
        "y": 20
      },
      "columns": 7,
      "rows": 6
    },
    {
      "hp": 21,
      "profile": "candidate-15",
      "origin": {
        "x": 8.19,
        "y": 20
      },
      "columns": 7,
      "rows": 6
    },
    {
      "hp": 21,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 7,
      "rows": 6
    },
    {
      "hp": 21,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 12.09,
        "y": 20
      },
      "columns": 7,
      "rows": 6
    },
    {
      "hp": 22,
      "profile": "candidate-15",
      "origin": {
        "x": 10.7,
        "y": 20
      },
      "columns": 7,
      "rows": 6
    },
    {
      "hp": 22,
      "profile": "candidate-15.24",
      "origin": {
        "x": 9.98,
        "y": 20
      },
      "columns": 7,
      "rows": 6
    },
    {
      "hp": 22,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 7.75,
        "y": 20
      },
      "columns": 8,
      "rows": 6
    },
    {
      "hp": 23,
      "profile": "candidate-15",
      "origin": {
        "x": 13.27,
        "y": 20
      },
      "columns": 7,
      "rows": 6
    },
    {
      "hp": 23,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 7,
      "rows": 6
    },
    {
      "hp": 23,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 10.32,
        "y": 20
      },
      "columns": 8,
      "rows": 6
    },
    {
      "hp": 24,
      "profile": "candidate-15",
      "origin": {
        "x": 8.31,
        "y": 20
      },
      "columns": 8,
      "rows": 6
    },
    {
      "hp": 24,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 8,
      "rows": 6
    },
    {
      "hp": 24,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 6.01,
        "y": 20
      },
      "columns": 9,
      "rows": 6
    },
    {
      "hp": 25,
      "profile": "candidate-15",
      "origin": {
        "x": 10.85,
        "y": 20
      },
      "columns": 8,
      "rows": 6
    },
    {
      "hp": 25,
      "profile": "candidate-15.24",
      "origin": {
        "x": 10.01,
        "y": 20
      },
      "columns": 8,
      "rows": 6
    },
    {
      "hp": 25,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 8.55,
        "y": 20
      },
      "columns": 9,
      "rows": 6
    },
    {
      "hp": 26,
      "profile": "candidate-15",
      "origin": {
        "x": 13.39,
        "y": 20
      },
      "columns": 8,
      "rows": 6
    },
    {
      "hp": 26,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 8,
      "rows": 6
    },
    {
      "hp": 26,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 11.09,
        "y": 20
      },
      "columns": 9,
      "rows": 6
    },
    {
      "hp": 27,
      "profile": "candidate-15",
      "origin": {
        "x": 8.43,
        "y": 20
      },
      "columns": 9,
      "rows": 6
    },
    {
      "hp": 27,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 9,
      "rows": 6
    },
    {
      "hp": 27,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 6.78,
        "y": 20
      },
      "columns": 10,
      "rows": 6
    },
    {
      "hp": 28,
      "profile": "candidate-15",
      "origin": {
        "x": 10.95,
        "y": 20
      },
      "columns": 9,
      "rows": 6
    },
    {
      "hp": 28,
      "profile": "candidate-15.24",
      "origin": {
        "x": 9.99,
        "y": 20
      },
      "columns": 9,
      "rows": 6
    },
    {
      "hp": 28,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 9.3,
        "y": 20
      },
      "columns": 10,
      "rows": 6
    },
    {
      "hp": 29,
      "profile": "candidate-15",
      "origin": {
        "x": 6.01,
        "y": 20
      },
      "columns": 10,
      "rows": 6
    },
    {
      "hp": 29,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 9,
      "rows": 6
    },
    {
      "hp": 29,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 11.86,
        "y": 20
      },
      "columns": 10,
      "rows": 6
    },
    {
      "hp": 30,
      "profile": "candidate-15",
      "origin": {
        "x": 8.55,
        "y": 20
      },
      "columns": 10,
      "rows": 6
    },
    {
      "hp": 30,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 10,
      "rows": 6
    },
    {
      "hp": 30,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 7.55,
        "y": 20
      },
      "columns": 11,
      "rows": 6
    },
    {
      "hp": 31,
      "profile": "candidate-15",
      "origin": {
        "x": 11.09,
        "y": 20
      },
      "columns": 10,
      "rows": 6
    },
    {
      "hp": 31,
      "profile": "candidate-15.24",
      "origin": {
        "x": 10.01,
        "y": 20
      },
      "columns": 10,
      "rows": 6
    },
    {
      "hp": 31,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 10.09,
        "y": 20
      },
      "columns": 11,
      "rows": 6
    },
    {
      "hp": 32,
      "profile": "candidate-15",
      "origin": {
        "x": 6.13,
        "y": 20
      },
      "columns": 11,
      "rows": 6
    },
    {
      "hp": 32,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 10,
      "rows": 6
    },
    {
      "hp": 32,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 12.63,
        "y": 20
      },
      "columns": 11,
      "rows": 6
    },
    {
      "hp": 33,
      "profile": "candidate-15",
      "origin": {
        "x": 8.67,
        "y": 20
      },
      "columns": 11,
      "rows": 6
    },
    {
      "hp": 33,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 11,
      "rows": 6
    },
    {
      "hp": 33,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 8.32,
        "y": 20
      },
      "columns": 12,
      "rows": 6
    },
    {
      "hp": 34,
      "profile": "candidate-15",
      "origin": {
        "x": 11.21,
        "y": 20
      },
      "columns": 11,
      "rows": 6
    },
    {
      "hp": 34,
      "profile": "candidate-15.24",
      "origin": {
        "x": 10.01,
        "y": 20
      },
      "columns": 11,
      "rows": 6
    },
    {
      "hp": 34,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 10.86,
        "y": 20
      },
      "columns": 12,
      "rows": 6
    },
    {
      "hp": 35,
      "profile": "candidate-15",
      "origin": {
        "x": 6.25,
        "y": 20
      },
      "columns": 12,
      "rows": 6
    },
    {
      "hp": 35,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 11,
      "rows": 6
    },
    {
      "hp": 35,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 6.55,
        "y": 20
      },
      "columns": 13,
      "rows": 6
    },
    {
      "hp": 36,
      "profile": "candidate-15",
      "origin": {
        "x": 8.79,
        "y": 20
      },
      "columns": 12,
      "rows": 6
    },
    {
      "hp": 36,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 12,
      "rows": 6
    },
    {
      "hp": 36,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 9.09,
        "y": 20
      },
      "columns": 13,
      "rows": 6
    },
    {
      "hp": 37,
      "profile": "candidate-15",
      "origin": {
        "x": 11.33,
        "y": 20
      },
      "columns": 12,
      "rows": 6
    },
    {
      "hp": 37,
      "profile": "candidate-15.24",
      "origin": {
        "x": 10.01,
        "y": 20
      },
      "columns": 12,
      "rows": 6
    },
    {
      "hp": 37,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 11.63,
        "y": 20
      },
      "columns": 13,
      "rows": 6
    },
    {
      "hp": 38,
      "profile": "candidate-15",
      "origin": {
        "x": 6.37,
        "y": 20
      },
      "columns": 13,
      "rows": 6
    },
    {
      "hp": 38,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 12,
      "rows": 6
    },
    {
      "hp": 38,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 7.32,
        "y": 20
      },
      "columns": 14,
      "rows": 6
    },
    {
      "hp": 39,
      "profile": "candidate-15",
      "origin": {
        "x": 8.91,
        "y": 20
      },
      "columns": 13,
      "rows": 6
    },
    {
      "hp": 39,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.47,
        "y": 20
      },
      "columns": 13,
      "rows": 6
    },
    {
      "hp": 39,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 9.86,
        "y": 20
      },
      "columns": 14,
      "rows": 6
    },
    {
      "hp": 40,
      "profile": "candidate-15",
      "origin": {
        "x": 11.45,
        "y": 20
      },
      "columns": 13,
      "rows": 6
    },
    {
      "hp": 40,
      "profile": "candidate-15.24",
      "origin": {
        "x": 10.01,
        "y": 20
      },
      "columns": 13,
      "rows": 6
    },
    {
      "hp": 40,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 12.4,
        "y": 20
      },
      "columns": 14,
      "rows": 6
    },
    {
      "hp": 41,
      "profile": "candidate-15",
      "origin": {
        "x": 6.49,
        "y": 20
      },
      "columns": 14,
      "rows": 6
    },
    {
      "hp": 41,
      "profile": "candidate-15.24",
      "origin": {
        "x": 12.55,
        "y": 20
      },
      "columns": 13,
      "rows": 6
    },
    {
      "hp": 41,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 8.09,
        "y": 20
      },
      "columns": 15,
      "rows": 6
    },
    {
      "hp": 42,
      "profile": "candidate-15",
      "origin": {
        "x": 9,
        "y": 20
      },
      "columns": 14,
      "rows": 6
    },
    {
      "hp": 42,
      "profile": "candidate-15.24",
      "origin": {
        "x": 7.44,
        "y": 20
      },
      "columns": 14,
      "rows": 6
    },
    {
      "hp": 42,
      "profile": "thonkiconn-13.7",
      "origin": {
        "x": 10.6,
        "y": 20
      },
      "columns": 15,
      "rows": 6
    }
  ],
  "rotations": [
    {
      "rotation": 0,
      "in": {
        "x": 3,
        "y": 1
      },
      "out": {
        "x": 3,
        "y": 1
      }
    },
    {
      "rotation": 90,
      "in": {
        "x": 3,
        "y": 1
      },
      "out": {
        "x": 1,
        "y": -3
      }
    },
    {
      "rotation": 180,
      "in": {
        "x": 3,
        "y": 1
      },
      "out": {
        "x": -3,
        "y": -1
      }
    },
    {
      "rotation": 270,
      "in": {
        "x": 3,
        "y": 1
      },
      "out": {
        "x": -1,
        "y": 3
      }
    }
  ]
};
  if (typeof module !== 'undefined' && module.exports) { module.exports = data; }
  root.PCBGEN_VECTORS = data;
})(typeof globalThis !== 'undefined' ? globalThis : this);
