// Generated by `cabal run pcbgen -- sketcher`; do not edit.
// The numbers come from toolkit/src/Sketch/Catalogue.hs.
(function (root) {
  var data = {
  "valid": [
    {
      "name": "mixer",
      "sketch": {
        "format": "module-sketch",
        "version": 2,
        "name": "Mixer",
        "columns": 3,
        "rows": 6,
        "cells": [
          {
            "col": 0,
            "row": 0,
            "kind": "knob",
            "label": "CH1"
          },
          {
            "col": 1,
            "row": 0,
            "kind": "jack",
            "label": "IN 1"
          },
          {
            "col": 0,
            "row": 1,
            "kind": "knob",
            "label": "CH2"
          },
          {
            "col": 1,
            "row": 1,
            "kind": "jack",
            "label": "IN 2"
          },
          {
            "col": 0,
            "row": 2,
            "kind": "knob",
            "label": "CH3"
          },
          {
            "col": 1,
            "row": 2,
            "kind": "jack",
            "label": "IN 3"
          },
          {
            "col": 0,
            "row": 3,
            "kind": "knob",
            "label": "CH4"
          },
          {
            "col": 1,
            "row": 3,
            "kind": "jack",
            "label": "IN 4"
          },
          {
            "col": 0,
            "row": 5,
            "kind": "switch",
            "label": "AC/DC"
          },
          {
            "col": 1,
            "row": 5,
            "kind": "jack",
            "label": "OUT"
          },
          {
            "col": 2,
            "row": 5,
            "kind": "led",
            "label": "CLIP"
          }
        ]
      },
      "text": "{\n  \"format\": \"module-sketch\",\n  \"version\": 2,\n  \"name\": \"Mixer\",\n  \"columns\": 3,\n  \"rows\": 6,\n  \"cells\": [\n    {\n      \"col\": 0,\n      \"row\": 0,\n      \"kind\": \"knob\",\n      \"label\": \"CH1\"\n    },\n    {\n      \"col\": 1,\n      \"row\": 0,\n      \"kind\": \"jack\",\n      \"label\": \"IN 1\"\n    },\n    {\n      \"col\": 0,\n      \"row\": 1,\n      \"kind\": \"knob\",\n      \"label\": \"CH2\"\n    },\n    {\n      \"col\": 1,\n      \"row\": 1,\n      \"kind\": \"jack\",\n      \"label\": \"IN 2\"\n    },\n    {\n      \"col\": 0,\n      \"row\": 2,\n      \"kind\": \"knob\",\n      \"label\": \"CH3\"\n    },\n    {\n      \"col\": 1,\n      \"row\": 2,\n      \"kind\": \"jack\",\n      \"label\": \"IN 3\"\n    },\n    {\n      \"col\": 0,\n      \"row\": 3,\n      \"kind\": \"knob\",\n      \"label\": \"CH4\"\n    },\n    {\n      \"col\": 1,\n      \"row\": 3,\n      \"kind\": \"jack\",\n      \"label\": \"IN 4\"\n    },\n    {\n      \"col\": 0,\n      \"row\": 5,\n      \"kind\": \"switch\",\n      \"label\": \"AC/DC\"\n    },\n    {\n      \"col\": 1,\n      \"row\": 5,\n      \"kind\": \"jack\",\n      \"label\": \"OUT\"\n    },\n    {\n      \"col\": 2,\n      \"row\": 5,\n      \"kind\": \"led\",\n      \"label\": \"CLIP\"\n    }\n  ]\n}\n",
      "hp": 10
    },
    {
      "name": "empty",
      "sketch": {
        "format": "module-sketch",
        "version": 2,
        "name": "Empty",
        "columns": 1,
        "rows": 1,
        "cells": []
      },
      "text": "{\n  \"format\": \"module-sketch\",\n  \"version\": 2,\n  \"name\": \"Empty\",\n  \"columns\": 1,\n  \"rows\": 1,\n  \"cells\": []\n}\n",
      "hp": 4
    }
  ],
  "invalid": [
    {
      "name": "wrong format",
      "text": "{\"format\": \"pcbgen-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 2, \"cells\": []}"
    },
    {
      "name": "wrong version",
      "text": "{\"format\": \"module-sketch\", \"version\": 1, \"columns\": 2, \"rows\": 2, \"cells\": []}"
    },
    {
      "name": "missing columns",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"rows\": 2, \"cells\": []}"
    },
    {
      "name": "missing cells",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 2}"
    },
    {
      "name": "zero columns",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 0, \"rows\": 2, \"cells\": []}"
    },
    {
      "name": "too many columns",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 7, \"rows\": 2, \"cells\": []}"
    },
    {
      "name": "too many rows",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 7, \"cells\": []}"
    },
    {
      "name": "fractional columns",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2.5, \"rows\": 2, \"cells\": []}"
    },
    {
      "name": "non-finite columns",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 1e999, \"rows\": 2, \"cells\": []}"
    },
    {
      "name": "NaN literal",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": NaN, \"rows\": 2, \"cells\": []}"
    },
    {
      "name": "cell off the grid",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 2, \"cells\": [{\"col\": 2, \"row\": 0, \"kind\": \"knob\"}]}"
    },
    {
      "name": "negative cell",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 2, \"cells\": [{\"col\": -1, \"row\": 0, \"kind\": \"knob\"}]}"
    },
    {
      "name": "two components in one cell",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 2, \"cells\": [{\"col\": 0, \"row\": 0, \"kind\": \"knob\"}, {\"col\": 0, \"row\": 0, \"kind\": \"jack\"}]}"
    },
    {
      "name": "unknown kind",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 2, \"cells\": [{\"col\": 0, \"row\": 0, \"kind\": \"banana\"}]}"
    },
    {
      "name": "missing kind",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 2, \"cells\": [{\"col\": 0, \"row\": 0}]}"
    },
    {
      "name": "unknown cell field",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 2, \"cells\": [{\"col\": 0, \"row\": 0, \"kind\": \"knob\", \"lcsc\": \"C1\"}]}"
    },
    {
      "name": "unknown top-level field",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 2, \"cells\": [], \"netlist\": []}"
    },
    {
      "name": "label too long",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 2, \"cells\": [{\"col\": 0, \"row\": 0, \"kind\": \"knob\", \"label\": \"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"}]}"
    },
    {
      "name": "not an object",
      "text": "[]"
    },
    {
      "name": "truncated",
      "text": "{\"format\": \"module-sketch\", \"version\": 2"
    },
    {
      "name": "trailing comma",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"rows\": 2, \"cells\": [],}"
    },
    {
      "name": "duplicate key",
      "text": "{\"format\": \"module-sketch\", \"version\": 2, \"columns\": 2, \"columns\": 3, \"rows\": 2, \"cells\": []}"
    },
    {
      "name": "empty text",
      "text": ""
    }
  ]
};
  if (typeof module !== 'undefined' && module.exports) { module.exports = data; }
  root.SKETCH_VECTORS = data;
})(typeof globalThis !== 'undefined' ? globalThis : this);
