{-# LANGUAGE OverloadedStrings #-}
-- | What the browser sketcher gets from the generator.
--
-- The sketcher runs from a plain file, where a page may not @fetch@ its
-- neighbours, so the shared data is shipped as JavaScript files that assign
-- one global each: @sketcher/catalogue.js@ (hardware, grid profiles and the
-- form-factor numbers, all taken from the Haskell that generates boards) and
-- @sketcher/vectors.js@ (the fixtures with their expected placements and
-- findings, and the texts that must be refused). The sketcher's own tests
-- run the JavaScript geometry against those vectors, which is what keeps one
-- set of panel dimensions in the project rather than two.
--
-- 'bundle' inlines the sketcher's assets into one HTML page for the fast-ui
-- exchange channel, prefixing the shared-storage hook that page relies on.
module Sketch.Export
  ( catalogueJs
  , vectorsJs
  , fixtureFiles
  , bundle
  , findingJson
  , placementJson
  ) where

import           Data.Text (Text)
import qualified Data.Text as T

import           Block.Eurorack
import           Design           (LibId (..), eurorackPanelHeight, eurorackPanelWidths, eurorackPcbHeight, eurorackPcbTop)
import           Route.Geometry   (rotatePt)
import           Sketch.Catalogue
import           Sketch.Check
import           Sketch.Fixtures
import           Sketch.Json
import           Sketch.Model

-- | Wrap a JSON value as a script that works both as a browser global and as
-- a CommonJS module, so the same file feeds the page and the node test run.
asScript :: Text -> JValue -> Text
asScript global v = T.unlines
  [ "// Generated by `cabal run pcbgen -- sketcher`; do not edit. The numbers"
  , "// come from toolkit/src/Sketch/*.hs and Block/Eurorack.hs."
  , "(function (root) {"
  , "  var data = " <> renderJson v <> ";"
  , "  if (typeof module !== 'undefined' && module.exports) { module.exports = data; }"
  , "  root." <> global <> " = data;"
  , "})(typeof globalThis !== 'undefined' ? globalThis : this);"
  ]

num :: Double -> JValue
num = JNumber

pt :: (Double, Double) -> JValue
pt (x, y) = JObject [("x", num x), ("y", num y)]

shapeJson :: Shape -> JValue
shapeJson (Circle d) = JObject [("shape", JString "circle"), ("d", num d)]
shapeJson (Rect w h) = JObject [("shape", JString "rect"), ("w", num w), ("h", num h)]

boxJson :: Box -> JValue
boxJson (Box x1 y1 x2 y2) = JObject [("x1", num x1), ("y1", num y1), ("x2", num x2), ("y2", num y2)]

evidenceJson :: Evidence -> JValue
evidenceJson e = JString (case e of InUse -> "in-use"; Proposed -> "proposed"; Unverified -> "unverified")

hardwareJson :: Hardware -> JValue
hardwareJson h = JObject
  [ ("id", JString (hwId h))
  , ("name", JString (hwName h))
  , ("role", JString (hwRole h))
  , ("hole", num (hwHoleDiameter h))
  , ("frontBody", shapeJson (hwFrontBody h))
  , ("frontAccess", maybe JNull shapeJson (hwFrontAccess h))
  , ("courtyard", boxJson (hwCourtyard h))
  , ("footprint", maybe JNull (\(LibId l n) -> JString (l <> ":" <> n)) (hwFootprint h))
  , ("anchor", pt (hwAnchor h))
  , ("rotations", JArray (map (num . fromIntegral) (hwRotations h)))
  , ("reservesCell", JBool (hwReservesCell h))
  , ("defaultRotation", num (fromIntegral (hwDefaultRotation h)))
  , ("height", num (hwHeight h))
  , ("status", evidenceJson (hwStatus h))
  , ("frontEvidence", evidenceJson (hwFrontEvidence h))
  , ("source", JString (hwSource h))
  , ("notes", JString (hwNotes h))
  ]

profileJson :: GridProfile -> JValue
profileJson p = JObject
  [ ("id", JString (gpId p))
  , ("pitch", pt (gpPitch p))
  , ("firstRow", num (gpFirstRow p))
  , ("status", JString (gpStatus p))
  , ("note", JString (gpNote p))
  ]

-- | Widths the sketcher may offer: Doepfer's table and the formula up to 42HP.
widths :: [Int]
widths = [1 .. 42]

skeletonJson :: Int -> JValue
skeletonJson hp =
  let sk = skeleton hp
  in JObject
       [ ("hp", num (fromIntegral hp))
       , ("panelWidth", num (skPanelWidth sk))
       , ("boardWidth", num (skBoardWidth sk))
       , ("boardHeight", num (skBoardHeight sk))
       , ("boardOrigin", pt (skBoardOrigin sk))
       , ("railHolesX", JArray (map num (skRailHoleX sk)))
       , ("railHolesY", JArray (map num (skRailHoleY sk)))
       ]

catalogueJs :: Text
catalogueJs = asScript "PCBGEN_CATALOGUE" $ JObject
  [ ("format", JString formatName)
  , ("version", num (fromIntegral formatVersion))
  , ("hardware", JArray (map hardwareJson catalogue))
  , ("profiles", JArray (map profileJson gridProfiles))
  , ("form", JObject
      [ ("panelHeight", num eurorackPanelHeight)
      , ("pcbHeight", num eurorackPcbHeight)
      , ("pcbTop", num eurorackPcbTop)
      , ("railHoleDiameter", num 3.2)
      , ("railKeepoutRadius", num railKeepoutRadius)
      , ("minCentreEdgeDistance", num minCentreEdgeDistance)
      , ("policyHP", JObject [("min", num 4), ("max", num 20)])
      , ("doepferTable", JArray [ num (fromIntegral hp) | (hp, _) <- eurorackPanelWidths ])
      ])
  , ("skeletons", JArray (map skeletonJson widths))
  , ("skeletonRule", JString "panelWidth from Doepfer's table or HP x 5.08 - 0.3; board 1 mm inside each side, 100 mm tall, centred; rail holes at x 7.5 and 7.5 + (HP - 3) x 5.08 (only when HP > 4), y 3 and 125.5")
  ]

placementJson :: Placement -> JValue
placementJson p = JObject
  [ ("id", JString (ctId (plControl p)))
  , ("centre", pt (plCentre p))
  , ("board", pt (plBoardCentre p))
  , ("footprintOrigin", pt (plFootprintOrigin p))
  , ("rotation", num (fromIntegral (ctRotation (plControl p))))
  , ("courtyard", boxJson (plCourtyard p))
  , ("frontBody", shapeJson (plFrontBody p))
  , ("frontAccess", maybe JNull shapeJson (plFrontAccess p))
  ]

findingJson :: Finding -> JValue
findingJson f = JObject
  [ ("kind", JString (fnKind f))
  , ("severity", JString (case fnSeverity f of Conflict -> "conflict"; Warning -> "warning"; Note -> "note"))
  , ("controls", JArray (map JString (fnControls f)))
  , ("message", JString (fnMessage f))
  ]

fixtureJson :: (Text, Sketch) -> JValue
fixtureJson (name, s) =
  let sk = skeleton (sxHP s)
  in JObject
       [ ("name", JString name)
       , ("sketch", encodeSketch s)
       , ("text", JString (encodeSketchText s))   -- the browser's stringify must match byte for byte
       , ("expected", JObject
           [ ("panelWidth", num (skPanelWidth sk))
           , ("boardOrigin", pt (skBoardOrigin sk))
           , ("railHoles", JArray [ pt (x, y) | x <- skRailHoleX sk, y <- skRailHoleY sk ])
           , ("controls", JArray (map placementJson (placeSketch s)))
           , ("findings", JArray (map findingJson (checkSketch s)))
           ])
       ]

vectorsJs :: Text
vectorsJs = asScript "PCBGEN_VECTORS" $ JObject
  [ ("valid", JArray (map fixtureJson fixtures))
  , ("invalid", JArray [ JObject [("name", JString n), ("text", JString t)] | (n, t) <- invalidTexts ])
  , ("gridDefaults", JArray
      [ JObject [ ("hp", num (fromIntegral hp)), ("profile", JString (gpId gp))
                , ("origin", pt (defaultGridOrigin hp gp))
                , ("columns", num (fromIntegral (columnsFor hp (fst (gpPitch gp)))))
                , ("rows", num (fromIntegral (rowsFor gp))) ]
      | hp <- widths, gp <- gridProfiles ])
  , ("rotations", JArray
      -- rotatePt at each quarter turn, so the browser's transform is checked directly
      [ JObject [("rotation", num (fromIntegral r)), ("in", pt (3, 1)), ("out", pt (rounded (rotatePt (fromIntegral r) (3, 1))))] | r <- [0, 90, 180, 270 :: Int] ])
  ]
  where
    -- rotatePt goes through cos and sin, which leave 1e-16 crumbs on quarter turns
    rounded (x, y) = (fromIntegral (round (x * 1e9) :: Integer) / 1e9, fromIntegral (round (y * 1e9) :: Integer) / 1e9)

-- | The reference files, relative to the repository root.
fixtureFiles :: [(FilePath, Text)]
fixtureFiles = [ ("sketches/_fixtures/" ++ T.unpack n ++ ".json", encodeSketchText s) | (n, s) <- fixtures ]

-- | Inline every local script and stylesheet of the sketcher page into one
-- HTML text, and make the fast-ui storage hook the first script, so the page
-- can be handed to @show_html@ as a self-contained string. @readAsset@
-- resolves a path relative to the sketcher directory.
bundle :: Text -> (Text -> IO Text) -> IO Text
bundle indexHtml readAsset = do
  ls <- mapM inline (T.lines indexHtml)
  pure (T.unlines (concat ls))
  where
    inline l
      | Just src <- attr "<script src=\"" l, local src = do
          js <- readAsset src
          pure ["<script>", "// " <> src, js, "</script>"]
      | Just href <- attr "<link rel=\"stylesheet\" href=\"" l, local href = do
          css <- readAsset href
          pure ["<style>", "/* " <> href <> " */", css, "</style>"]
      | "<head>" `T.isInfixOf` l = pure [l, "<script src=\"/sharedLocalStorage.js\"></script>"]
      | otherwise = pure [l]
    local u = not ("/" `T.isPrefixOf` u) && not ("://" `T.isInfixOf` u)
    attr prefix l =
      let t = T.strip l
      in if prefix `T.isPrefixOf` t
           then Just (T.takeWhile (/= '"') (T.drop (T.length prefix) t))
           else Nothing
