{-# LANGUAGE OverloadedStrings #-}
-- | What the browser sketcher gets from the generator.
--
-- The sketcher runs from a plain file, where a page may not @fetch@ its
-- neighbours, so this ships as JavaScript that assigns one global each:
-- @sketcher/catalogue.js@ (the kinds a cell can hold and how big the grid may
-- be) and @sketcher/vectors.js@ (the fixtures and the texts that must be
-- refused). The browser therefore never carries its own copy of the limits.
--
-- 'bundle' inlines the page's assets into one HTML text for the fast-ui
-- exchange channel, with the shared-storage hook in front.
module Sketch.Export
  ( catalogueJs
  , vectorsJs
  , fixtureFiles
  , bundle
  , limitsReport
  ) where

import           Data.Text        (Text)
import qualified Data.Text        as T

import           Sketch.Catalogue
import           Sketch.Fixtures
import           Sketch.Json
import           Sketch.Model

asScript :: Text -> JValue -> Text
asScript global v = T.unlines
  [ "// Generated by `cabal run pcbgen -- sketcher`; do not edit."
  , "// The numbers come from toolkit/src/Sketch/Catalogue.hs."
  , "(function (root) {"
  , "  var data = " <> renderJson v <> ";"
  , "  if (typeof module !== 'undefined' && module.exports) { module.exports = data; }"
  , "  root." <> global <> " = data;"
  , "})(typeof globalThis !== 'undefined' ? globalThis : this);"
  ]

num :: Int -> JValue
num = JNumber . fromIntegral

catalogueJs :: Text
catalogueJs = asScript "SKETCH_CATALOGUE" $ JObject
  [ ("format", JString formatName)
  , ("version", num formatVersion)
  , ("kinds", JArray [ JObject [ ("id", JString (kindId k)), ("label", JString (kindLabel k))
                               , ("note", JString (kindNote k)) ] | k <- kinds ])
  , ("maxColumns", num maxColumns)
  , ("maxRows", num maxRows)
    -- What each column count would cost in panel width. The editor shows
    -- this as a note; it is the only place HP is mentioned.
  , ("widthForColumns", JArray
      [ JObject [ ("columns", num n), ("hp", maybe JNull num (smallestWidthFor n)) ]
      | n <- [1 .. maxColumns] ])
  , ("why", JString limitsReport)
  ]

-- | One sentence a person can check, rather than two numbers to take on
-- trust. The editor prints it under the grid controls.
limitsReport :: Text
limitsReport =
  "At " <> mm gridPitch <> " spacing a 100 mm board leaves " <> mm (glBand gridLimits)
  <> " of travel for control centres, so " <> T.pack (show maxRows) <> " rows fit; "
  <> T.pack (show (maxRows + 1)) <> " would space them " <> mm (glRowPitchAt gridLimits (maxRows + 1))
  <> " apart and two 3.5 mm jacks need " <> mm jackStackMinimum
  <> ". Columns stop at " <> T.pack (show maxColumns)
  <> " because that already needs the widest panel the module policy allows."
  where
    mm d = T.pack (trim (show (fromIntegral (round (d * 100) :: Integer) / 100 :: Double))) <> " mm"
    trim t | ".0" `T.isSuffixOf` T.pack t = take (length t - 2) t
           | otherwise = t

vectorsJs :: Text
vectorsJs = asScript "SKETCH_VECTORS" $ JObject
  [ ("valid", JArray
      [ JObject [ ("name", JString n)
                , ("sketch", encodeSketch s)
                , ("text", JString (encodeSketchText s))
                , ("hp", maybe JNull num (impliedWidth s)) ]
      | (n, s) <- fixtures ])
  , ("invalid", JArray [ JObject [("name", JString n), ("text", JString t)] | (n, t) <- invalidTexts ])
  ]

fixtureFiles :: [(FilePath, Text)]
fixtureFiles = [ ("sketches/_fixtures/" ++ T.unpack n ++ ".json", encodeSketchText s) | (n, s) <- fixtures ]

-- | Inline every local script and stylesheet of the sketcher page into one
-- HTML text, and make the fast-ui storage hook the first script.
bundle :: Text -> (Text -> IO Text) -> IO Text
bundle indexHtml readAsset = do
  ls <- mapM inline (T.lines indexHtml)
  pure (T.unlines (concat ls))
  where
    inline l
      | Just src <- attr "<script src=\"" l, local src = do
          js <- readAsset src
          pure ["<script>", "// " <> src, js, "</script>"]
      | Just href <- attr "<link rel=\"stylesheet\" href=\"" l, local href = do
          css <- readAsset href
          pure ["<style>", "/* " <> href <> " */", css, "</style>"]
      | "<head>" `T.isInfixOf` l = pure [l, "<script src=\"/sharedLocalStorage.js\"></script>"]
      | otherwise = pure [l]
    local u = not ("/" `T.isPrefixOf` u) && not ("://" `T.isInfixOf` u)
    attr prefix l =
      let t = T.strip l
      in if prefix `T.isPrefixOf` t
           then Just (T.takeWhile (/= '"') (T.drop (T.length prefix) t))
           else Nothing
