{-# LANGUAGE OverloadedStrings #-}
-- | Emit the project file (.kicad_pro) and custom DRC rules (.kicad_dru).
-- The project file is JSON; KiCad only needs the design-rule and net-class
-- sections to run DRC headlessly, the rest are its own defaults.
module Emit.Project (emitProject, emitDru) where

import           Data.Text (Text)
import qualified Data.Text as T

import           Design
import           Kicad.SExpr (mm)

emitDru :: Module -> Text
emitDru m = T.unlines ["(version 1)", "", bdCustomRules (modBoard m)]

emitProject :: Module -> Text -> Text
emitProject m sheetUuid =
  let r = bdRules (modBoard m)
      name = modName m
  in T.unlines
  [ "{"
  , "  \"board\": {"
  , "    \"3dviewports\": [],"
  , "    \"design_settings\": {"
  , "      \"defaults\": {"
  , "        \"board_outline_line_width\": 0.05,"
  , "        \"copper_line_width\": 0.2,"
  , "        \"copper_text_size_h\": 1.5,"
  , "        \"copper_text_size_v\": 1.5,"
  , "        \"copper_text_thickness\": 0.3,"
  , "        \"courtyard_line_width\": 0.05,"
  , "        \"fab_line_width\": 0.1,"
  , "        \"fab_text_size_h\": 1.0,"
  , "        \"fab_text_size_v\": 1.0,"
  , "        \"fab_text_thickness\": 0.15,"
  , "        \"other_line_width\": 0.1,"
  , "        \"other_text_size_h\": 1.0,"
  , "        \"other_text_size_v\": 1.0,"
  , "        \"other_text_thickness\": 0.15,"
  , "        \"silk_line_width\": 0.1,"
  , "        \"silk_text_size_h\": 1.0,"
  , "        \"silk_text_size_v\": 1.0,"
  , "        \"silk_text_thickness\": 0.1,"
  , "        \"zones\": {"
  , "          \"min_clearance\": 0.3,"
  , "          \"min_thickness\": 0.25,"
  , "          \"thermal_relief_gap\": 0.5,"
  , "          \"thermal_relief_spoke_width\": 0.5"
  , "        }"
  , "      },"
  , "      \"drc_exclusions\": [],"
  , "      \"meta\": { \"version\": 2 },"
  , "      \"rule_severities\": {"
  , "        \"courtyards_overlap\": \"error\","
  , "        \"hole_to_hole\": \"error\","
  , "        \"lib_footprint_mismatch\": \"error\","
  , "        \"footprint_symbol_field_mismatch\": \"error\","
  , "        \"silk_over_copper\": \"warning\","
  , "        \"silk_overlap\": \"warning\","
  , "        \"solder_mask_bridge\": \"error\","
  , "        \"nonmirrored_text_on_back_layer\": \"error\","
  , "        \"zones_intersect\": \"error\""
  , "      },"
  , "      \"rules\": {"
  , "        \"max_error\": 0.005,"
  , "        \"min_clearance\": " <> mm (drClearance r) <> ","
  , "        \"min_connection\": 0.0,"
  , "        \"min_copper_edge_clearance\": " <> mm (drEdgeClearance r) <> ","
  , "        \"min_hole_clearance\": 0.25,"
  , "        \"min_hole_to_hole\": " <> mm (drHoleToHole r) <> ","
  , "        \"min_microvia_diameter\": 0.2,"
  , "        \"min_microvia_drill\": 0.1,"
  , "        \"min_resolved_spokes\": 2,"
  , "        \"min_silk_clearance\": 0.0,"
  , "        \"min_text_height\": 0.8,"
  , "        \"min_text_thickness\": 0.08,"
  , "        \"min_through_hole_diameter\": " <> mm (drViaDrill r) <> ","
  , "        \"min_track_width\": " <> mm (drTrackWidth r) <> ","
  , "        \"min_via_annular_width\": 0.1,"
  , "        \"min_via_diameter\": " <> mm (drViaDiameter r) <> ","
  , "        \"solder_mask_to_copper_clearance\": 0.0,"
  , "        \"use_height_for_length_calcs\": true"
  , "      },"
  , "      \"track_widths\": [],"
  , "      \"via_dimensions\": [],"
  , "      \"zones_allow_external_fillets\": false"
  , "    },"
  , "    \"layer_presets\": [],"
  , "    \"viewports\": []"
  , "  },"
  , "  \"boards\": [],"
  , "  \"cvpcb\": { \"equivalence_files\": [] },"
  , "  \"libraries\": { \"pinned_footprint_libs\": [], \"pinned_symbol_libs\": [] },"
  , "  \"meta\": { \"filename\": \"" <> name <> ".kicad_pro\", \"version\": 3 },"
  , "  \"net_settings\": {"
  , "    \"classes\": ["
  , "      {"
  , "        \"bus_width\": 12,"
  , "        \"clearance\": " <> mm (drClearance r) <> ","
  , "        \"diff_pair_gap\": 0.25,"
  , "        \"diff_pair_via_gap\": 0.25,"
  , "        \"diff_pair_width\": 0.2,"
  , "        \"line_style\": 0,"
  , "        \"microvia_diameter\": 0.3,"
  , "        \"microvia_drill\": 0.1,"
  , "        \"name\": \"Default\","
  , "        \"pcb_color\": \"rgba(0, 0, 0, 0.000)\","
  , "        \"priority\": 2147483647,"
  , "        \"schematic_color\": \"rgba(0, 0, 0, 0.000)\","
  , "        \"track_width\": " <> mm (drTrackWidth r) <> ","
  , "        \"via_diameter\": " <> mm (drViaDiameter r) <> ","
  , "        \"via_drill\": " <> mm (drViaDrill r) <> ","
  , "        \"wire_width\": 6"
  , "      }"
  , "    ],"
  , "    \"meta\": { \"version\": 5 },"
  , "    \"net_colors\": null,"
  , "    \"netclass_assignments\": null,"
  , "    \"netclass_patterns\": []"
  , "  },"
  , "  \"pcbnew\": {"
  , "    \"last_paths\": { \"idf\": \"\", \"netlist\": \"\", \"plot\": \"\", \"specctra_dsn\": \"\", \"step\": \"\", \"vrml\": \"\" },"
  , "    \"page_layout_descr_file\": \"\""
  , "  },"
  , "  \"schematic\": {"
  , "    \"bus_aliases\": {},"
  , "    \"legacy_lib_dir\": \"\","
  , "    \"legacy_lib_list\": [],"
  , "    \"top_level_sheets\": ["
  , "      { \"filename\": \"" <> name <> ".kicad_sch\", \"name\": \"" <> name <> "\", \"uuid\": \"" <> sheetUuid <> "\" }"
  , "    ]"
  , "  },"
  , "  \"sheets\": [],"
  , "  \"text_variables\": {}"
  , "}"
  ]
