{-# LANGUAGE OverloadedStrings #-}
-- | Emit a KiCad 10 schematic (.kicad_sch) from a 'Module'.
--
-- Layout strategy is deliberately simple and mechanical: every symbol sits
-- where the design says, every pin gets a short stub, and the stub ends in a
-- net label (signal nets), a power symbol (power nets) or a no-connect flag.
-- That is less pretty than hand-drawn buses but it is generic, always
-- electrically correct, and ERC-clean.
module Emit.Schematic
  ( emitSchematic
  , SchInfo (..)
  , SymInfo (..)
  ) where

import           Data.List       (nub)
import qualified Data.Map.Strict as M
import           Data.Maybe      (fromMaybe)
import           Data.Text       (Text)
import qualified Data.Text       as T

import           Design
import           Kicad.Library
import           Kicad.SExpr
import           Kicad.Uuid

-- | What the PCB emitter needs to know about the schematic it must match.
data SchInfo = SchInfo
  { siSheetUuid :: Text
  , siSymbols   :: M.Map Text SymInfo   -- ^ by reference
  }

data SymInfo = SymInfo
  { symUuid        :: Text
  , symDescription :: Text
  , symPinNames    :: [(Text, Text)]    -- ^ (pin number, pin name)
  }

type Pt = (Double, Double)

-- | Screen-space rotation (y down) by a multiple of 90 degrees, CCW as seen.
rotScreen :: Double -> Pt -> Pt
rotScreen a (x, y)
  | a' == 90  = (y, -x)
  | a' == 180 = (-x, -y)
  | a' == 270 = (-y, x)
  | otherwise = (x, y)
  where a' = fromIntegral (round a `mod` (360 :: Int)) :: Double

-- | Library offset (y up) to screen offset (y down), then rotate.
libToScreen :: Double -> Pt -> Pt
libToScreen a (x, y) = rotScreen a (x, -y)

add :: Pt -> Pt -> Pt
add (a, b) (c, d) = (a + c, b + d)

scale :: Double -> Pt -> Pt
scale k (x, y) = (k * x, k * y)

-- | Unit direction pointing away from the symbol body, in screen space.
outward :: Double -> PinDef -> Pt
outward rot p =
  let a = pinAngle p + 180
      r = a * pi / 180
      v = (cos r, sin r)            -- library frame, y up
  in quantize (libToScreen rot v)
  where
    quantize (x, y)
      | abs x >= abs y = (signum x, 0)
      | otherwise      = (0, signum y)

labelAngle :: Pt -> Double
labelAngle (1, _)  = 0
labelAngle (-1, _) = 180
labelAngle (_, -1) = 90
labelAngle _       = 270

-- | Power symbol rotation whose body continues along the given direction.
powerRot :: Pt -> Double
powerRot (1, _)  = 90
powerRot (-1, _) = 270
powerRot (_, -1) = 180
powerRot _       = 0

emitSchematic :: LibCache -> Module -> IO (Text, SchInfo)
emitSchematic lc m = do
  let name = modName m
      sheetUuid = uuidFor (name <> "/sheet")
      u s = uuidFor (name <> "/" <> s)
      pinNet = M.fromList [ ((r, p), n) | n <- modNets m, (r, p) <- netPins n ]
      powerNets = [ n | n <- modNets m, netKind n == Power ]

  -- Library symbols used by parts, plus power symbols and the PWR_FLAG.
  partSyms <- mapM (\p -> (,) (partSymbol p) <$> loadSymbol lc (libNick (partSymbol p)) (libItem (partSymbol p))) (modParts m)
  powerSyms <- mapM (\n -> (,) (LibId "power" (netName n)) <$> loadSymbol lc "power" (netName n)) powerNets
  flagSym <- loadSymbol lc "power" "PWR_FLAG"
  let symTable = M.fromList (partSyms ++ powerSyms ++ [(LibId "power" "PWR_FLAG", flagSym)])
      libSymbols = list "lib_symbols" (nub (M.elems symTable))

  let partItems = concatMap (emitPart symTable pinNet u sheetUuid name) (modParts m)

  -- One PWR_FLAG + power symbol pair per power net, parked at the right-hand
  -- side of the A4 sheet, one below the other.
  let flagBase = (228.6, 50.8)
      flags = concat
        [ powerPair symTable u sheetUuid name ("FLG" <> T.pack (show i)) (netName n) (add flagBase (0, 20.32 * fromIntegral (i - 1)))
        | (i, n) <- zip [1 :: Int ..] powerNets ]

  -- Free text at the bottom-left corner of the A4 sheet, left of the title block.
  let notes = [ List [ Atom "text", Str (T.intercalate "\n" (modNotes m))
                     , list "exclude_from_sim" [sym "no"]
                     , list "at" [num 25.4, num 190.5, num 0]
                     , list "effects" [list "font" [list "size" [num 2, num 2]], list "justify" [sym "left", sym "bottom"]]
                     , list "uuid" [Str (u "notes")] ]
              | not (null (modNotes m)) ]

  let sch = List $
        [ Atom "kicad_sch"
        , list "version" [sym "20250610"]
        , list "generator" [Str "pcbgen"]
        , list "generator_version" [Str "10.0"]
        , list "uuid" [Str sheetUuid]
        , list "paper" [Str "A4"]
        , list "title_block" [list "title" [Str (modTitle m)], list "comment" [num 1, Str ("Generated by pcbgen from toolkit/src/Designs; do not edit by hand")]]
        , libSymbols
        ] ++ partItems ++ flags ++ notes ++
        [ list "sheet_instances" [list "path" [Str "/", list "page" [Str "1"]]]
        , list "embedded_fonts" [sym "no"]
        ]

  let info = SchInfo sheetUuid $ M.fromList
        [ (partRef p, SymInfo (u ("sym/" <> partRef p))
                               (fromMaybe "" (symbolPropertyValue "Description" s))
                               [ (pinNumber d, pinName d) | d <- symbolPins s ])
        | p <- modParts m, Just s <- [M.lookup (partSymbol p) symTable] ]
  pure (render sch, info)

-- | Symbol instance plus the stubs, labels, power symbols and no-connects on
-- its pins.
emitPart :: M.Map LibId SExpr -> M.Map (Text, Text) Net -> (Text -> Text) -> Text -> Text -> Part -> [SExpr]
emitPart symTable pinNet u sheetUuid proj p =
  let s = fromMaybe (error ("no symbol for " ++ T.unpack (partRef p))) (M.lookup (partSymbol p) symTable)
      ref = partRef p
      pos = partSchAt p
      rot = partSchRot p
      instanceE = symbolInstance u sheetUuid proj (partSymbol p) s ref (partValue p) (Just (partFootprint p)) (partFields p) pos rot False
      pins = symbolPins s
      pinItems = concat
        [ case M.lookup (ref, pinNumber d) pinNet of
            Nothing -> [ List [Atom "no_connect", list "at" [num px, num py], list "uuid" [Str (u ("nc/" <> ref <> "/" <> pinNumber d))]] ]
            Just n | netKind n == Signal ->
              let q = add pt (scale 2.54 dir)
              in [ wire u (ref <> "/" <> pinNumber d <> "/stub") pt q
                 , label u (ref <> "/" <> pinNumber d) (netName n) q (labelAngle dir) ]
            Just n ->
              powerDrop symTable u sheetUuid proj (ref <> "_" <> pinNumber d) (netName n) pt dir (snd pt < snd pos)
        | d <- pins
        , let pt@(px, py) = add pos (libToScreen rot (pinX d, pinY d))
        , let dir = outward rot d
        ]
  in instanceE : pinItems

-- | Stub away from a pin and a power symbol at its end. Horizontal pins get a
-- second, vertical stub so the symbol does not sit in the neighbouring pin's
-- label.
powerDrop :: M.Map LibId SExpr -> (Text -> Text) -> Text -> Text -> Text -> Text -> Pt -> Pt -> Bool -> [SExpr]
powerDrop symTable u sheetUuid proj key net pt dir up
  | snd dir == 0 =
      let q1 = add pt (scale 2.54 dir)
          q2 = add q1 (0, if up then -2.54 else 2.54)
          rot = if up then 180 else 0
      in [ wire u (key <> "/stub1") pt q1, wire u (key <> "/stub2") q1 q2
         , powerSymbol symTable u sheetUuid proj ("PWR_" <> key) net q2 rot ]
  | otherwise =
      let q = add pt (scale 2.54 dir)
      in [ wire u (key <> "/stub") pt q
         , powerSymbol symTable u sheetUuid proj ("PWR_" <> key) net q (powerRot dir) ]

-- | A power symbol whose pin lands exactly on @pt@.
powerSymbol :: M.Map LibId SExpr -> (Text -> Text) -> Text -> Text -> Text -> Text -> Pt -> Double -> SExpr
powerSymbol symTable u sheetUuid proj ref net pt rot =
  let lid = LibId "power" net
      s = fromMaybe (error ("no power symbol " ++ T.unpack net)) (M.lookup lid symTable)
      pinOff = case symbolPins s of
        (d : _) -> libToScreen rot (pinX d, pinY d)
        []      -> (0, 0)
      pos = add pt (scale (-1) pinOff)
  in symbolInstance u sheetUuid proj lid s ("#" <> ref) net Nothing [] pos rot True

-- | PWR_FLAG and a power symbol sharing one point, for nets no output drives.
powerPair :: M.Map LibId SExpr -> (Text -> Text) -> Text -> Text -> Text -> Text -> Pt -> [SExpr]
powerPair symTable u sheetUuid proj key net pt =
  let flagLid = LibId "power" "PWR_FLAG"
      fs = fromMaybe (error "no PWR_FLAG") (M.lookup flagLid symTable)
      pinOff = case symbolPins fs of
        (d : _) -> libToScreen 0 (pinX d, pinY d)
        []      -> (0, 0)
  in [ symbolInstance u sheetUuid proj flagLid fs ("#" <> key) "PWR_FLAG" Nothing [] (add pt (scale (-1) pinOff)) 0 True
     , powerSymbol symTable u sheetUuid proj ("PWR_" <> key) net pt 0 ]

symbolInstance :: (Text -> Text) -> Text -> Text -> LibId -> SExpr -> Text -> Text -> Maybe LibId -> [(Text, Text)] -> Pt -> Double -> Bool -> SExpr
symbolInstance u sheetUuid proj lid s ref val fp extra pos@(x, y) rot isPower =
  let libId = libNick lid <> ":" <> libItem lid
      symU = u ("sym/" <> ref)
      propAt name = case symbolPropertyAt name s of
        Just (ox, oy, _) -> add pos (libToScreen rot (ox, oy))
        Nothing          -> pos
      prop name value hidden =
        let (px, py) = propAt name
        in List $ [ Atom "property", Str name, Str value
                  , list "at" [num px, num py, num rot] ]
                  ++ [ list "hide" [sym "yes"] | hidden ]
                  ++ [ list "effects" [list "font" [list "size" [num 1.27, num 1.27]]] ]
      fpText = maybe "" (\l -> libNick l <> ":" <> libItem l) fp
      desc = fromMaybe "" (symbolPropertyValue "Description" s)
      datasheet = fromMaybe "" (lookup "Datasheet" extra)
      extraProps = [ prop k v True | (k, v) <- extra, k /= "Datasheet" ]
      pins = [ List [Atom "pin", Str (pinNumber d), list "uuid" [Str (u ("pin/" <> ref <> "/" <> pinNumber d))]] | d <- symbolPins s ]
      -- Library symbols carry their own BOM/simulation flags (solder jumpers
      -- are in_bom no); the instance must agree or the footprint parity check
      -- complains.
      flag name def = case findChild name s of
        Just (List [_, Atom v]) -> v
        _                       -> def
  in List $
       [ Atom "symbol"
       , list "lib_id" [Str libId]
       , list "at" [num x, num y, num rot]
       , list "unit" [num 1]
       , list "exclude_from_sim" [sym (flag "exclude_from_sim" "no")]
       , list "in_bom" [sym (if isPower then "no" else flag "in_bom" "yes")]
       , list "on_board" [sym (flag "on_board" "yes")]
       , list "dnp" [sym "no"]
       , list "uuid" [Str symU]
       , prop "Reference" ref isPower
       , prop "Value" val False
       , prop "Footprint" fpText True
       , prop "Datasheet" datasheet True
       , prop "Description" desc True
       ] ++ extraProps ++ pins ++
       [ list "instances" [list "project" [Str proj, list "path" [Str ("/" <> sheetUuid), list "reference" [Str ref], list "unit" [num 1]]]] ]

wire :: (Text -> Text) -> Text -> Pt -> Pt -> SExpr
wire u key (x1, y1) (x2, y2) =
  List [ Atom "wire"
       , list "pts" [list "xy" [num x1, num y1], list "xy" [num x2, num y2]]
       , list "stroke" [list "width" [num 0], list "type" [sym "default"]]
       , list "uuid" [Str (u ("wire/" <> key))] ]

label :: (Text -> Text) -> Text -> Text -> Pt -> Double -> SExpr
label u key net (x, y) angle =
  let justify = if angle == 0 || angle == 90 then [sym "left", sym "bottom"] else [sym "right", sym "bottom"]
  in List [ Atom "label", Str net
          , list "at" [num x, num y, num angle]
          , list "effects" [list "font" [list "size" [num 1.27, num 1.27]], list "justify" justify]
          , list "uuid" [Str (u ("label/" <> key))] ]
